models:
  path: /home/mbahgat/ws/work/models/phd_framework

datasets:
  clpysch:
    task_a:
      path:
        train: /home/mbahgat/ws/work/jws/clpysch/data/task_A_train.posts.json
        test: /home/mbahgat/ws/work/jws/clpysch/data/task_A_test.posts.json

  affect_in_tweets:
    path:
      train: /home/mbahgat/ws/work/datasets/affect_in_tweets/2018-EI-oc-En-all-train.tsv
      dev: /home/mbahgat/ws/work/datasets/affect_in_tweets/2018-EI-oc-En-all-dev.tsv
      test: /home/mbahgat/ws/work/datasets/affect_in_tweets/2018-EI-oc-En-all-test.tsv

  emocontext:
    classify_emotions:
      path:
        train: /home/mbahgat/ws/work/datasets/emo_context/parts/3_class/train.tsv
        dev: /home/mbahgat/ws/work/datasets/emo_context/parts/3_class/dev.tsv
        test: /home/mbahgat/ws/work/datasets/emo_context/parts/3_class/test.tsv

    emotions_vs_none: 
      path:
        train: /home/mbahgat/ws/work/datasets/emo_context/parts/2_class/train.tsv
        dev: /home/mbahgat/ws/work/datasets/emo_context/parts/2_class/dev.tsv
        test: /home/mbahgat/ws/work/datasets/emo_context/parts/2_class/test.tsv

    classify_all:
      path:
        train: /home/mbahgat/ws/work/datasets/emo_context/parts/2_class/train.tsv
        dev: /home/mbahgat/ws/work/datasets/emo_context/parts/2_class/dev.tsv
        test: /home/mbahgat/ws/work/datasets/emo_context/parts/2_class/test.tsv


  agnews:
    path:
      train: /home/mbahgat/ws/work/datasets/CharCnn_Keras/data/ag_news_csv/train.csv
      test: /home/mbahgat/ws/work/datasets/CharCnn_Keras/data/ag_news_csv/test.csv

  emonet:
    path: /home/mbahgat/ws/work/datasets/emo_net/emo_net_8class.tsv
      
  ud_liwc_best_v1:
    path:
      train: /home/mbahgat/ws/work/datasets/urban_dict/liwc_tagged/ud_data_best_def_train.csv
      test: /home/mbahgat/ws/work/datasets/urban_dict/liwc_tagged/ud_data_best_def_test.csv
  
  ud_liwc:
    liwc14:
      exact:
        test: /home/mbahgat/ws/work/datasets/urban_dict/liwc_tagged_v2.1/14class/liwc14_ud_test.csv
        train:
          all: /home/mbahgat/ws/work/datasets/urban_dict/liwc_tagged_v2.1/14class/liwc14_ud_train_exact.csv
          top1: /home/mbahgat/ws/work/datasets/urban_dict/liwc_tagged_v2.1/14class/liwc14_ud_train_exact_top1.csv
          top10: /home/mbahgat/ws/work/datasets/urban_dict/liwc_tagged_v2.1/14class/liwc14_ud_train_exact_top10.csv
          mindiff1: /home/mbahgat/ws/work/datasets/urban_dict/liwc_tagged_v2.1/14class/liwc14_ud_train_exact_mindiff1.csv
          mindiff10: /home/mbahgat/ws/work/datasets/urban_dict/liwc_tagged_v2.1/14class/liwc14_ud_train_exact_mindiff10.csv
      all:
        train: 
          all: /home/mbahgat/ws/work/datasets/urban_dict/liwc_tagged_v2.1/14class/liwc14_ud_train.csv
          top1: /home/mbahgat/ws/work/datasets/urban_dict/liwc_tagged_v2.1/14class/liwc14_ud_train_top1.csv

liwc:
  path: /home/mbahgat/ws/work/resources/LIWC2015_English_Flat.dic